# Use custom format
format = """
[â”Œ](bold green)$time$shell$status$cmd_duration
[â”‚](bold green) $username$hostname$directory$git_branch$rust$python$java$golang
[â””](bold green)$character
"""

# Disables blank line between shell prompts
add_newline = false

# Makes prompt a two lines instead of one
[line_break]
disabled = false

# Replace the "â¯" symbol in the prompt with "âœ"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[âœ](bold green)"     # The "success_symbol" segment is being set to "âœ" with the color "bold green"
error_symbol = "[âœ](bold red)"

# Username style options
[username]
disabled = false
style_user = "bold green"
style_root = "bold red"
format = "[$user]($style) "
show_always = true

# Directory options
[directory]
truncation_length = 5
truncation_symbol = ".../"
truncate_to_repo = false

# Command duration
[cmd_duration]
disabled = false
min_time = 10000
format = "ran for [$duration](bold yellow)"

# Hostname info
[hostname]
disabled = false
ssh_only = false
format = "at [$hostname](bold dimmed green) in "

# Memory usage
[memory_usage]
disabled = true
threshold = -1

# Time
[time]
disabled = false
format = '[\[ $time \]]($style) '
time_format = "%r"
utc_time_offset = "-7"
use_12hr = true

# Shell indicator
[shell]
disabled = false
bash_indicator = "ğŸ”¨"
fish_indicator = "ğŸŸ"
zsh_indicator = "ğŸ‡¿"
unknown_indicator = "â“"
format = "$indicator "

# Command status
[status]
disabled = false
sigint_symbol = "ğŸ›‘"
map_symbol = true
format = '[\[$symbol $common_meaning$signal_name$maybe_int\]]($style) '
